server:
  port: 8001
  servlet:
    context-path: /community

community:
  path:
    domain: http://localhost:80
    upload: /Users/zouderun/source_for_community/data/upload

mybatis:
  type-aliases-package: com.swim.community.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

spring:
  application:
    name: springcloud-provider-user
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  mail:
    host: smtp.163.com
    port: 465
    username: xxxxxx@163.com
    password: XXXXXXXXXX
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  redis:
    database: 11
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: springcloud-provider-user8001  # 修改eureka上的默认描述信息
    prefer-ip-address: true

info:
  app.name: swim-community-springcloud
  company.name: xxx.xxx.xxx


