server:
  port: 80
  servlet:
    context-path: /community

# 开启降级feign hystrix
feign:
  hystrix:
    enabled: false

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eureka/
    # fetch-registry: true

spring:
  data:
    elasticsearch:
      cluster-name: swim
      cluster-nodes: 127.0.0.1:9300
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  redis:
    database: 11
    host: localhost
    port: 6379
  mail:
    host: smtp.163.com
    port: 465
    username: xxxx@163.com
    password: XXXXXXXXX
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
  task:
    execution:
      pool:
        core-size: 5
        max-size: 15
        queue-capacity: 100
    scheduling:
      pool:
        size: 5
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000

community:
  path:
    domain: http://localhost:80
    upload: /Users/zouderun/source_for_community/data/upload

wk:
  image:
    storage: /Users/zouderun/wk-images
    command: /usr/local/bin/wkhtmltoimage

logging:
  level:
    com:
      swim:
        community: debug